version: '3.8'
services:
  dicom-server:
    image: dcm4che/dcm4chee-arc-psql:5.24.1
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: dicom_research
      POSTGRES_USER: dicom_admin
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
